# Generated by Django 5.2.5 on 2025-09-09 04:56

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_update_post_content_to_richtext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(help_text='เนื้อหาบทความ - รองรับการอัปโหลดรูปภาพ'),
        ),
    ]
