# Generated by Django 4.2.16 on 2025-09-11 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_facebookpage_facebookpost_facebookinsight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookpage',
            name='client_token',
            field=models.CharField(blank=True, help_text='Facebook Client Token', max_length=100),
        ),
    ]
