# Generated by Django 4.2.16 on 2025-09-12 01:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0007_facebookpage_client_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostAnalyticsSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='ปี')),
                ('month', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], verbose_name='เดือน')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('twitter', 'Twitter'), ('tiktok', 'TikTok'), ('youtube', 'YouTube')], max_length=20, verbose_name='แพลตฟอร์ม')),
                ('total_posts', models.PositiveIntegerField(default=0, verbose_name='จำนวนโพสต์')),
                ('total_likes', models.PositiveIntegerField(default=0, verbose_name='รวม Like')),
                ('total_comments', models.PositiveIntegerField(default=0, verbose_name='รวม Comment')),
                ('total_shares', models.PositiveIntegerField(default=0, verbose_name='รวม Share')),
                ('total_views', models.PositiveIntegerField(default=0, verbose_name='รวม View')),
                ('avg_engagement', models.FloatField(default=0.0, verbose_name='เฉลี่ย Engagement')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='สร้างเมื่อ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='อัปเดตเมื่อ')),
            ],
            options={
                'verbose_name': 'สรุปสถิติโพสต์',
                'verbose_name_plural': 'สรุปสถิติโพสต์',
                'ordering': ['-year', '-month', 'platform'],
            },
        ),
        migrations.CreateModel(
            name='SocialPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='หัวข้อโพสต์')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('twitter', 'Twitter'), ('tiktok', 'TikTok'), ('youtube', 'YouTube')], default='facebook', max_length=20, verbose_name='แพลตฟอร์ม')),
                ('post_url', models.URLField(blank=True, null=True, verbose_name='ลิงก์โพสต์')),
                ('content_preview', models.TextField(blank=True, help_text='เนื้อหาโพสต์ (ย่อ)', verbose_name='เนื้อหาโพสต์')),
                ('likes_count', models.PositiveIntegerField(default=0, verbose_name='จำนวน Like')),
                ('comments_count', models.PositiveIntegerField(default=0, verbose_name='จำนวน Comment')),
                ('shares_count', models.PositiveIntegerField(default=0, verbose_name='จำนวน Share')),
                ('views_count', models.PositiveIntegerField(default=0, help_text='สำหรับ Video posts', verbose_name='จำนวน View')),
                ('post_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='วันที่โพสต์')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='สร้างเมื่อ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='อัปเดตเมื่อ')),
                ('is_active', models.BooleanField(default=True, verbose_name='เปิดใช้งาน')),
                ('notes', models.TextField(blank=True, verbose_name='หมายเหตุ')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='สร้างโดย')),
            ],
            options={
                'verbose_name': 'โพสต์โซเชียล',
                'verbose_name_plural': 'โพสต์โซเชียล',
                'ordering': ['-post_date'],
            },
        ),
        migrations.RemoveField(
            model_name='facebookapilog',
            name='page',
        ),
        migrations.RemoveField(
            model_name='facebookcomment',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='facebookcomment',
            name='post',
        ),
        migrations.AlterUniqueTogether(
            name='facebookinsight',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='facebookinsight',
            name='page',
        ),
        migrations.RemoveField(
            model_name='facebookinsight',
            name='post',
        ),
        migrations.RemoveField(
            model_name='facebookpost',
            name='page',
        ),
        migrations.DeleteModel(
            name='FacebookAnalyticsSnapshot',
        ),
        migrations.DeleteModel(
            name='FacebookApiLog',
        ),
        migrations.DeleteModel(
            name='FacebookComment',
        ),
        migrations.DeleteModel(
            name='FacebookInsight',
        ),
        migrations.DeleteModel(
            name='FacebookPage',
        ),
        migrations.DeleteModel(
            name='FacebookPost',
        ),
        migrations.AddField(
            model_name='postanalyticssummary',
            name='best_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.socialpost', verbose_name='โพสต์ที่ดีที่สุด'),
        ),
        migrations.AlterUniqueTogether(
            name='postanalyticssummary',
            unique_together={('year', 'month', 'platform')},
        ),
    ]
