# Generated by Django 4.2.16 on 2025-09-20 02:28

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='รูปปกวิดีโอ', null=True, upload_to=blog.models.upload_video_thumbnail),
        ),
        migrations.AddField(
            model_name='video',
            name='thumbnail_alt',
            field=models.CharField(blank=True, help_text='Alt text สำหรับรูปปก', max_length=200),
        ),
    ]
