# Generated by Django 4.2.16 on 2025-09-30 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_video_thumbnail_video_thumbnail_alt'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='ชื่อประเภท')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='คำอธิบาย')),
                ('icon', models.CharField(blank=True, help_text='CSS icon class or emoji', max_length=20, verbose_name='ไอคอน')),
                ('color', models.CharField(default='#3B82F6', help_text='Hex color code', max_length=7, verbose_name='สีประจำประเภท')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ประเภทโพสต์',
                'verbose_name_plural': 'ประเภทโพสต์',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blog.posttype', verbose_name='ประเภทโพสต์'),
        ),
    ]
