# Generated by Django 4.2.16 on 2025-10-08 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_posttype_post_post_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialpost',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='PostAnalyticsSummary',
        ),
        migrations.DeleteModel(
            name='SocialPost',
        ),
    ]
