# Generated by Django 4.2.16 on 2025-10-08 03:49

import blog.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0012_remove_socialpost_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='ชื่อแบบสำรวจ')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='คำอธิบาย')),
                ('survey_file', models.FileField(blank=True, help_text='อัปโหลดไฟล์ Word (.docx) หรือ Excel (.xlsx, .xls)', null=True, upload_to=blog.models.upload_survey_file, verbose_name='ไฟล์แบบสำรวจ')),
                ('status', models.CharField(choices=[('draft', 'ร่าง'), ('active', 'เปิดรับคำตอบ'), ('closed', 'ปิดรับคำตอบ'), ('archived', 'เก็บถาวร')], default='draft', max_length=10, verbose_name='สถานะ')),
                ('allow_multiple_responses', models.BooleanField(default=False, verbose_name='อนุญาตตอบหลายครั้ง')),
                ('require_login', models.BooleanField(default=False, verbose_name='ต้องเข้าสู่ระบบ')),
                ('show_results', models.BooleanField(default=True, verbose_name='แสดงผลลัพธ์')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='วันเริ่มต้น')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='วันสิ้นสุด')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('response_count', models.PositiveIntegerField(default=0, verbose_name='จำนวนผู้ตอบ')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='จำนวนครั้งที่เข้าชม')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to=settings.AUTH_USER_MODEL, verbose_name='ผู้สร้าง')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surveys', to='blog.category', verbose_name='หมวดหมู่')),
            ],
            options={
                'verbose_name': 'แบบสำรวจ',
                'verbose_name_plural': 'แบบสำรวจ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_data', models.JSONField(blank=True, default=dict, verbose_name='ข้อมูลคำตอบ')),
                ('response_file', models.FileField(blank=True, help_text='อัปโหลดไฟล์ Word/Excel ที่กรอกข้อมูลแล้ว', null=True, upload_to=blog.models.upload_survey_file, verbose_name='ไฟล์คำตอบ')),
                ('respondent_email', models.EmailField(blank=True, max_length=254, verbose_name='อีเมลผู้ตอบ')),
                ('respondent_name', models.CharField(blank=True, max_length=200, verbose_name='ชื่อผู้ตอบ')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='ส่งคำตอบเมื่อ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='แก้ไขล่าสุด')),
                ('is_complete', models.BooleanField(default=True, verbose_name='เสร็จสมบูรณ์')),
                ('is_verified', models.BooleanField(default=False, verbose_name='ตรวจสอบแล้ว')),
                ('respondent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_responses', to=settings.AUTH_USER_MODEL, verbose_name='ผู้ตอบ')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='blog.survey', verbose_name='แบบสำรวจ')),
            ],
            options={
                'verbose_name': 'คำตอบแบบสำรวจ',
                'verbose_name_plural': 'คำตอบแบบสำรวจ',
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['-submitted_at'], name='blog_survey_submitt_05b26a_idx'), models.Index(fields=['survey', '-submitted_at'], name='blog_survey_survey__3009d2_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='survey',
            index=models.Index(fields=['-created_at'], name='blog_survey_created_569df8_idx'),
        ),
        migrations.AddIndex(
            model_name='survey',
            index=models.Index(fields=['status'], name='blog_survey_status_f0abe0_idx'),
        ),
        migrations.AddIndex(
            model_name='survey',
            index=models.Index(fields=['slug'], name='blog_survey_slug_140d33_idx'),
        ),
    ]
