# Generated by Django 4.2.16 on 2025-10-08 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_survey_surveyresponse_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='survey',
            name='blog_survey_status_f0abe0_idx',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='status',
        ),
        migrations.AddField(
            model_name='survey',
            name='is_published',
            field=models.BooleanField(default=False, help_text='เผยแพร่เอกสารการสำรวจให้สาธารณะเห็น', verbose_name='เผยแพร่'),
        ),
        migrations.AddField(
            model_name='survey',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='เผยแพร่เมื่อ'),
        ),
        migrations.AddField(
            model_name='survey',
            name='survey_date',
            field=models.DateField(blank=True, help_text='วันที่ทำการสำรวจ', null=True, verbose_name='วันที่สำรวจ'),
        ),
        migrations.AddIndex(
            model_name='survey',
            index=models.Index(fields=['is_published'], name='blog_survey_is_publ_238008_idx'),
        ),
    ]
