# Generated by Django 4.2.16 on 2025-10-08 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_remove_survey_blog_survey_status_f0abe0_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='allow_multiple_responses',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='require_login',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='show_results',
        ),
    ]
