# Generated by Django 4.2.16 on 2025-10-09 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_remove_survey_allow_multiple_responses_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='response_count',
        ),
        migrations.AddField(
            model_name='survey',
            name='respondent_count',
            field=models.PositiveIntegerField(default=0, help_text='จำนวนผู้ตอบแบบสำรวจ (คน)', verbose_name='จำนวนผู้ตอบแบบสำรวจ'),
        ),
        migrations.DeleteModel(
            name='SurveyResponse',
        ),
    ]
