# Generated by Django 5.2.5 on 2026-08-18 09:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_remove_survey_response_count_survey_respondent_count_and_more'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='source',
            field=models.CharField(blank=True, choices=[('facebook', 'Facebook')], help_text='ว่างไว้ถ้าเขียนเอง', max_length=20, verbose_name='ที่มา'),
        ),
        migrations.AddField(
            model_name='post',
            name='source_id',
            field=models.CharField(blank=True, default=None, help_text='กันนำเข้าซ้ำ', max_length=100, null=True, unique=True, verbose_name='รหัสโพสต์ต้นทาง'),
        ),
        migrations.AddField(
            model_name='post',
            name='source_url',
            field=models.URLField(blank=True, help_text='ลิงก์กลับไปโพสต์ต้นฉบับ', max_length=500, verbose_name='ลิงก์ต้นทาง'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['source'], name='blog_post_source_acd5d7_idx'),
        ),
    ]
