# Generated by Django 5.2.5 on 2026-08-18 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_post_source_post_source_id_post_source_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='source',
            field=models.CharField(blank=True, choices=[('facebook', 'Facebook')], help_text='ว่างไว้ถ้าเพิ่มเอง', max_length=20, verbose_name='ที่มา'),
        ),
        migrations.AddField(
            model_name='video',
            name='source_id',
            field=models.CharField(blank=True, default=None, help_text='กันนำเข้าซ้ำ', max_length=100, null=True, unique=True, verbose_name='รหัสโพสต์ต้นทาง'),
        ),
    ]
